# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: joystick.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='joystick.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0ejoystick.proto\":\n\x08Joystick\x12\x13\n\x04\x61xes\x18\x01 \x01(\x0b\x32\x05.Axes\x12\x19\n\x07\x62uttons\x18\x02 \x01(\x0b\x32\x08.Buttons\"Q\n\x04\x41xes\x12\r\n\x05\x61xis0\x18\x01 \x01(\x02\x12\r\n\x05\x61xis1\x18\x02 \x01(\x02\x12\r\n\x05\x61xis2\x18\x03 \x01(\x02\x12\r\n\x05\x61xis3\x18\x04 \x01(\x02\x12\r\n\x05\x61xis4\x18\x05 \x01(\x02\"\xb3\x01\n\x07\x42uttons\x12\x0f\n\x07\x62utton0\x18\x01 \x01(\x05\x12\x0f\n\x07\x62utton1\x18\x02 \x01(\x05\x12\x0f\n\x07\x62utton2\x18\x03 \x01(\x05\x12\x0f\n\x07\x62utton3\x18\x04 \x01(\x05\x12\x0f\n\x07\x62utton4\x18\x05 \x01(\x05\x12\x0f\n\x07\x62utton5\x18\x06 \x01(\x05\x12\x0f\n\x07\x62utton6\x18\x07 \x01(\x05\x12\x0f\n\x07\x62utton7\x18\x08 \x01(\x05\x12\x0f\n\x07\x62utton8\x18\t \x01(\x05\x12\x0f\n\x07\x62utton9\x18\n \x01(\x05\x62\x06proto3')
)




_JOYSTICK = _descriptor.Descriptor(
  name='Joystick',
  full_name='Joystick',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='axes', full_name='Joystick.axes', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buttons', full_name='Joystick.buttons', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=76,
)


_AXES = _descriptor.Descriptor(
  name='Axes',
  full_name='Axes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='axis0', full_name='Axes.axis0', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='axis1', full_name='Axes.axis1', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='axis2', full_name='Axes.axis2', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='axis3', full_name='Axes.axis3', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='axis4', full_name='Axes.axis4', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=159,
)


_BUTTONS = _descriptor.Descriptor(
  name='Buttons',
  full_name='Buttons',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='button0', full_name='Buttons.button0', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='button1', full_name='Buttons.button1', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='button2', full_name='Buttons.button2', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='button3', full_name='Buttons.button3', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='button4', full_name='Buttons.button4', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='button5', full_name='Buttons.button5', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='button6', full_name='Buttons.button6', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='button7', full_name='Buttons.button7', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='button8', full_name='Buttons.button8', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='button9', full_name='Buttons.button9', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=341,
)

_JOYSTICK.fields_by_name['axes'].message_type = _AXES
_JOYSTICK.fields_by_name['buttons'].message_type = _BUTTONS
DESCRIPTOR.message_types_by_name['Joystick'] = _JOYSTICK
DESCRIPTOR.message_types_by_name['Axes'] = _AXES
DESCRIPTOR.message_types_by_name['Buttons'] = _BUTTONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Joystick = _reflection.GeneratedProtocolMessageType('Joystick', (_message.Message,), dict(
  DESCRIPTOR = _JOYSTICK,
  __module__ = 'joystick_pb2'
  # @@protoc_insertion_point(class_scope:Joystick)
  ))
_sym_db.RegisterMessage(Joystick)

Axes = _reflection.GeneratedProtocolMessageType('Axes', (_message.Message,), dict(
  DESCRIPTOR = _AXES,
  __module__ = 'joystick_pb2'
  # @@protoc_insertion_point(class_scope:Axes)
  ))
_sym_db.RegisterMessage(Axes)

Buttons = _reflection.GeneratedProtocolMessageType('Buttons', (_message.Message,), dict(
  DESCRIPTOR = _BUTTONS,
  __module__ = 'joystick_pb2'
  # @@protoc_insertion_point(class_scope:Buttons)
  ))
_sym_db.RegisterMessage(Buttons)


# @@protoc_insertion_point(module_scope)
